# Generated by Django 3.2.6 on 2022-07-07 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('FASHION', '0002_product_brand'),
    ]

    operations = [
        migrations.CreateModel(
            name='adreessManager',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(default='', max_length=50)),
                ('PIN', models.IntegerField(default=0)),
                ('Add', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(default='', max_length=50)),
                ('cart_item', models.TextField(null=True)),
            ],
        ),
    ]
